name: "Hello Actions"
description: "Test first action"
author: "stargazer4@github.com"

inputs:
  MY_NAME:
    description: "Who to greet"
    required: true
    default: "Sir"

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "mic"
  color: "purple"
