name: Team awesome's approval workflow
on: pull_request_review
jobs:
  labelWhenApproved:
    name: Label when approved job name 
    runs-on: ubuntu-latest
    steps:
      - name: NAME - using label when approved action 
        uses: actions/label-when-approved-action@main
        env:
          APPROVALS: "1"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
          ADD_LABEL: "APPROVED!!!!"
