name: A workflow for my Hello World file
on: push

env:
  TEST1: saad
  TEST2: khalid

jobs:
  build:
    env: 
      TEST3: eh
    name: " will this work ${{env.TEST3}} "
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: custom action a
        if: ${{ env.TEST1 == 'saad'}}
        uses: ./action-a
        with:
          MY_NAME: "stargazer $TEST1 $TEST2"
