name: A workflow for my Hello World file
on: push

env:
  TEST1: saad
  TEST2: khalid

jobs:
  build:
    name: Hello world action ${{env.TEST1}} ${{env.TEST2}} 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "stargazer $TEST1 $TEST2"
